version: "3"
services:
  nginx:
    image: nginx-simple:latest
    container_name: simple-nginx
    restart: always
    network_mode: "bridge"
    ports:
      - "8080:8080"
    volumes:
      - ./wwwroot/:/var/www/
    build:
      context: .
